name: "Sync Repo To GitLab"
description: "Sync a repository from GitHub to GitLab"
branding:
  icon: "share"
  color: "orange"
inputs:
  ssh_private_key:
    description: "SSH private key for ssh connection to the target repository"
    required: false
  target_repo_url:
    description: "Target url"
    required: true
  source_branch:
    description: "Source branch"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
